[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build -w front && npm run build -w back && npm run copy:frontend"

[start]
cmd = "npm run start:production" 